<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
      <RootNamespace>Todo.Infrastructure</RootNamespace>
    <AssemblyName>Todo.Infrastructure</AssemblyName>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="xunit.assert" Version="2.9.3" />
    <PackageReference Include="xunit.extensibility.core" Version="2.9.3" />
  </ItemGroup>
  
  <ItemGroup>
    <Reference Include="ToDo">
      <HintPath>..\tests\Application.Tests\bin\Debug\net9.0\ToDo.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
