### Get /
GET https://localhost:7214/
Accept: application/json

### Get all todos
GET https://localhost:7214/todos
Accept: application/json

### Get todo by ID
GET https://localhost:7214/todos/1
Accept: application/json

### Create a new todo
POST https://localhost:7214/todos
Content-Type: application/json

{
  "title": "title"
}

### Patch a Todo
PATCH https://localhost:7214/todos/1
Content-Type: application/json

[
  {
      "op": "replace",
      "path": "/title",
      "value": "Patched Title"
  },
  {
    "op": "replace",
    "path": "/order",
    "value": 4
  }
]

### Delete todo by ID
DELETE https://localhost:7214/todos/1

### Delete all Todos
DELETE https://localhost:7214/todos/
